### ISSUE TITLE
Remove "build" step from docker-compose automatically

### ISSUE THREAD

**Issue by Kuhno92** [ScaleIT-ORG/scaleit-public-catalog#8]
Rancher does not support build in docker-compose files for the catalog entry...
so it would be great if the autload.sh script would automatically remove this line for the catalog docker-compose

**Comment by Kuhno92** [comment]
Would be also create to automatically add the image name which will be created from docker-compose build to the catalog entry so you can later just run docker-compose build on the host machine to create the catalog images

**Comment by frostyandy2k** [comment]
Give an example of the above, I don't understand it yet. And there may be a word missing in your first sentence.

**Comment by Kuhno92** [comment]
Ok example: 

 imagine this is your docker-compose file from the desired application you want to add to the catalog:

```
version: '2'
services:
  web:
    build: Domain Software/.
    ports:
     - "5000:5000"
```

so the current script just copy n paste this to the catalog entry which causes an error on rancher because "build" is not supported from the catalog.
So the script should remove this tag and instead add the image name (image musst be available on the host system) like this:

```
version: '2'
services:
  web:
    image: myImageName
    ports:
     - "5000:5000"
```

myImageName should be the imagename generated from docker-compose.
There are 2 ways to do this.
 1.) Withoud specifying the imagename in the main docker-compose file `docker compose up` will the create an image named something like folderName_serviceName
 2.) Image name can be specified in the application docker-compose file by adding an `image` tag bevore the `build` tag like this:

```
version: '2'
services:
  web:
    image: myDesiredImageName
    build: Domain Software/.
    ports:
     - "5000:5000"
```
